spring.application.name=batch-processing-demo
spring.datasource.url=jdbc:postgresql://localhost:5432/sftp_ingestion
spring.datasource.username=sftp_app
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
sftp.host=localhost
sftp.port=2222
sftp.username=demo
sftp.password=demo123
sftp.remote-directory=upload
sftp.local-directory=D:/sravani_projects/sftp-demo/local-input
sftp.archive-directory=/opt/files/archive
sftp.error-directory=/opt/files/error